# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=8, unique=True)),
                ('nmae', models.CharField(max_length=50)),
                ('DOB', models.DateField(verbose_name='Date Of Birth')),
                ('Branch', models.CharField(choices=[('aero', 'Aerospace'), ('civil', 'Civil'), ('cse', 'Computer Science'), ('ece', 'Electronics & Communication'), ('elec', 'Electrical'), ('mech', 'Mechanical'), ('meta', 'Materials & Metallurgical'), ('prod', 'Production & Industrial')], default='aero', max_length=4)),
                ('Year_Of_Study', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', max_length=1)),
                ('Semester', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8)], default='1', max_length=1)),
                ('Contact_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
    ]
