# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 06:18
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=8, unique=True)),
                ('CourseName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyID', models.CharField(max_length=8, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=30)),
                ('ContactNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Email', models.EmailField(max_length=254)),
                ('User', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Course')),
                ('FacultyUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('CourseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Course')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Contact_Number',
            new_name='ContactNumber',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='nmae',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Student_ID',
            new_name='StudentID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Year_Of_Study',
        ),
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='User',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='YearOfStudy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='Branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='StudentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
