# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Course',
            field=models.CharField(default='CSN101', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 0, 17, 38, 615236)),
        ),
    ]
